services:
  mongo:
    image: mongo:8.0
    container_name: variedmcforum-local-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - variedmcforum_mongo_data:/data/db

volumes:
  variedmcforum_mongo_data:
