'use strict';

const baseDefinitions = [
	{ tag: '标签', bgColor: '#CDDC39', textColor: '#333333' },
	{ tag: '材质', bgColor: '#E65100', textColor: '#FFFFFF' },
	{ tag: '材质包', bgColor: '#FF9800', textColor: '#FFFFFF' },
	{ tag: '插件开发', bgColor: '#607D8B', textColor: '#FFFFFF' },
	{ tag: '村民交易', bgColor: '#795548', textColor: '#FFFFFF' },
	{ tag: '地物生成', bgColor: '#A1887F', textColor: '#FFFFFF' },
	{ tag: '方块交互', bgColor: '#616161', textColor: '#FFFFFF' },
	{ tag: '附魔', bgColor: '#673AB7', textColor: '#FFFFFF' },
	{ tag: '工作方块', bgColor: '#78909C', textColor: '#FFFFFF' },
	{ tag: '光影', bgColor: '#2196F3', textColor: '#FFFFFF' },
	{ tag: '光照系统', bgColor: '#FFC107', textColor: '#333333' },
	{ tag: '函数', bgColor: '#2196F3', textColor: '#FFFFFF' },
	{ tag: '红石机械', bgColor: '#F44336', textColor: '#FFFFFF' },
	{ tag: '机器', bgColor: '#546E7A', textColor: '#FFFFFF' },
	{ tag: '计分板', bgColor: '#37474F', textColor: '#FFFFFF' },
	{ tag: '结构生成', bgColor: '#6D4C41', textColor: '#FFFFFF' },
	{ tag: '进度', bgColor: '#4CAF50', textColor: '#FFFFFF' },
	{ tag: '粒子效果', bgColor: '#AD1457', textColor: '#FFFFFF' },
	{ tag: '聊天组件', bgColor: '#009688', textColor: '#FFFFFF' },
	{ tag: '流体', bgColor: '#0288D1', textColor: '#FFFFFF' },
	{ tag: '命令', bgColor: '#424242', textColor: '#FFFFFF' },
	{ tag: '命令方块', bgColor: '#795548', textColor: '#FFFFFF' },
	{ tag: '模型', bgColor: '#BF360C', textColor: '#FFFFFF' },
	{ tag: '模组开发', bgColor: '#9C27B0', textColor: '#FFFFFF' },
	{ tag: '模组联动', bgColor: '#5E35B1', textColor: '#FFFFFF' },
	{ tag: '模组魔改', bgColor: '#3949AB', textColor: '#FFFFFF' },
	{ tag: '能源', bgColor: '#FBC02D', textColor: '#333333' },
	{ tag: '配方', bgColor: '#8BC34A', textColor: '#FFFFFF' },
	{ tag: '权限', bgColor: '#D32F2F', textColor: '#FFFFFF' },
	{ tag: '容器', bgColor: '#F9A825', textColor: '#333333' },
	{ tag: '伤害系统', bgColor: '#C62828', textColor: '#FFFFFF' },
	{ tag: '生物', bgColor: '#4CAF50', textColor: '#FFFFFF' },
	{ tag: '生物交互', bgColor: '#2E7D32', textColor: '#FFFFFF' },
	{ tag: '生物群系', bgColor: '#689F38', textColor: '#FFFFFF' },
	{ tag: '实体', bgColor: '#388E3C', textColor: '#FFFFFF' },
	{ tag: '世界交互', bgColor: '#1976D2', textColor: '#FFFFFF' },
	{ tag: '世界生成', bgColor: '#8D6E63', textColor: '#FFFFFF' },
	{ tag: '世界数据', bgColor: '#607D8B', textColor: '#FFFFFF' },
	{ tag: '事件处理', bgColor: '#4527A0', textColor: '#FFFFFF' },
	{ tag: '数据包', bgColor: '#4CAF50', textColor: '#FFFFFF' },
	{ tag: '数据操作', bgColor: '#455A64', textColor: '#FFFFFF' },
	{ tag: '玩家数据', bgColor: '#3F51B5', textColor: '#FFFFFF' },
	{ tag: '网络通信', bgColor: '#2E3440', textColor: '#FFFFFF' },
	{ tag: '危险行为', bgColor: '#A73232', textColor: '#FFFFFF' },
	{ tag: '维度', bgColor: '#512DA8', textColor: '#FFFFFF' },
	{ tag: '维度类型', bgColor: '#673AB7', textColor: '#FFFFFF' },
	{ tag: '谓词', bgColor: '#FF9800', textColor: '#FFFFFF' },
	{ tag: '物品', bgColor: '#FFC107', textColor: '#333333' },
	{ tag: '物品交互', bgColor: '#F57C00', textColor: '#FFFFFF' },
	{ tag: '物品栏', bgColor: '#558B2F', textColor: '#FFFFFF' },
	{ tag: '物品提示', bgColor: '#37474F', textColor: '#FFFFFF' },
	{ tag: '物品修饰器', bgColor: '#E91E63', textColor: '#FFFFFF' },
	{ tag: '性能优化', bgColor: '#0277BD', textColor: '#FFFFFF' },
	{ tag: '渲染', bgColor: '#FF5722', textColor: '#FFFFFF' },
	{ tag: '药水效果', bgColor: '#8E24AA', textColor: '#FFFFFF' },
	{ tag: '音效', bgColor: '#6A4C93', textColor: '#FFFFFF' },
	{ tag: '战利品', bgColor: '#FF9800', textColor: '#FFFFFF' },
	{ tag: '着色器', bgColor: '#1565C0', textColor: '#FFFFFF' },
	{ tag: '整合包制作', bgColor: '#E91E63', textColor: '#FFFFFF' },
	{ tag: '指令系统', bgColor: '#607D8B', textColor: '#FFFFFF' },
	{ tag: '注册系统', bgColor: '#7C4DFF', textColor: '#FFFFFF' },
	{ tag: 'ai行为', bgColor: '#9C27B0', textColor: '#FFFFFF' },
	{ tag: 'brain', bgColor: '#8E24AA', textColor: '#FFFFFF' },
	{ tag: 'crafttweaker', bgColor: '#795548', textColor: '#FFFFFF' },
	{ tag: 'execute', bgColor: '#1A237E', textColor: '#FFFFFF' },
	{ tag: 'fabric', bgColor: '#DBD0B4', textColor: '#111111' },
	{ tag: 'forge', bgColor: '#DFA86A', textColor: '#FAF4F3' },
	{ tag: 'function', bgColor: '#0D47A1', textColor: '#FFFFFF' },
	{ tag: 'gamerule', bgColor: '#263238', textColor: '#FFFFFF' },
	{ tag: 'goal', bgColor: '#7B1FA2', textColor: '#FFFFFF' },
	{ tag: 'gui', bgColor: '#00838F', textColor: '#FFFFFF' },
	{ tag: 'hud', bgColor: '#00695C', textColor: '#FFFFFF' },
	{ tag: 'kubejs', bgColor: '#C186E6', textColor: '#FFFFFF' },
	{ tag: 'nbt操作', bgColor: '#6A1B9A', textColor: '#FFFFFF' },
	{ tag: 'neoforge', bgColor: '#E68C37', textColor: '#FFFFFF' },
	{ tag: 'restore', bgColor: '#1565C0', textColor: '#FFFFFF' },
	{ tag: 'team', bgColor: '#455A64', textColor: '#FFFFFF' },
	{ tag: 'unsafe', bgColor: '#A73232', textColor: '#FFFFFF' },
];

module.exports = baseDefinitions.map(definition => ({
	tag: definition.tag,
	lightBgColor: definition.bgColor,
	lightTextColor: definition.textColor,
	darkBgColor: definition.bgColor,
	darkTextColor: definition.textColor,
}));
